import glob
import os
import shutil
import sys

# Moves all scatter plots and histograms generated by search.py to centralized locations

try:
    detector = str(sys.argv[1])
except IndexError:
    print('Remember to specify the dates and detector!')

s_path = 'Collected Images/Scatter Plots/'
if not os.path.exists(s_path):
    os.makedirs(s_path)

h_path = 'Collected Images/Histograms/'
if not os.path.exists(h_path):
    os.makedirs(h_path)

detector_path = f'/home/jacob/search/Results/{detector}/'

days = glob.glob(f'{detector_path}*')

for day in days:
    # Scatter plots:
    scatter_plot_list = glob.glob(f'{day}/scatterplots/*event*.png')
    for s_file in scatter_plot_list:
        s_filename = s_file.replace(day, '')[14:]
        shutil.copyfile(s_file, f'{s_path}{s_filename}')

    # Histograms
    histogram_list = glob.glob(f'{day}/*histogram.png')
    for h_file in histogram_list:
        h_filename = h_file.replace(day, '')[1:]
        shutil.copyfile(h_file, f'{h_path}{h_filename}')

